=== hanaacharania/flamencometronome/src/main/resources/dtd/jcompas_estilo_v1.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT estilo (compas)>
<!ATTLIST estilo
	refId		CDATA			#REQUIRED
	paloRefId	CDATA			#REQUIRED>

<!ELEMENT compas (beat+)>
<!ATTLIST compas
	bpm			CDATA			#REQUIRED>

<!ELEMENT beat EMPTY>
<!ATTLIST beat
	name		CDATA			#REQUIRED
	strong		(true|false)	"false">

=== hanaacharania/flamencometronome/src/main/resources/patterns/estilos/siguiriyas.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE estilo SYSTEM "jcompas_estilo_v1.dtd">

<estilo refId="Siguiriya en 5" paloRefId="Siguiriya">
		<compas bpm="100">
			<beat name="1" strong="true"/>
			<beat name="" strong="false"/>
			<beat name="2" strong="true"/>
			<beat name="" strong="false"/>
			<beat name="3" strong="true"/>
			<beat name="" strong="false"/>
			<beat name="" strong="false"/>
			<beat name="4" strong="true"/>
			<beat name="" strong="false"/>
			<beat name="" strong="false"/>
			<beat name="5" strong="true"/>
			<beat name="" strong="false"/>
		</compas>
</estilo>
